### ISSUE TITLE
Continuous auto-increment

### ISSUE THREAD

**Issue by djjudas21** [camerahub/camerahub#145]
Find a more intelligent way of allocating auto increment IDs per-user (so every user has cameras 1, 2, 3, 4, etc)

**Comment by jgazeleyfr** [comment]
The correct way to do this is with an `F()` expression https://docs.djangoproject.com/en/2.2/ref/models/expressions/#f-expressions

Something like
```python
Invoice.objects.filter(owner=request.user).aggregate(Max('number'))
```

Embedded in an overriden save def https://docs.djangoproject.com/en/2.2/topics/db/models/#overriding-predefined-model-methods
