### ISSUE TITLE
The `add-path` command is disabled REOPEN

### ISSUE THREAD

**Issue by mcat56** [camerahub/camerahub#673]
Error in github actions pipeline with Install Poetry

```
Error: Unable to process command '##[add-path]/home/runner/.poetry/bin' successfully.

Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by djjudas21** [comment]
Hey, thanks for reporting. Can you give some more context about where you're seeing this, please? I'm not getting this error when running my github ations against `master` just now: https://github.com/djjudas21/camerahub/actions/runs/431199122

**Comment by djjudas21** [comment]
I haven't got any more detail on this issue and I haven't been able to reproduce it myself, so I'm going to close this. Please reopen if you've got more information - thanks :+1:
